
const express = require('express');
const authRouter = require('./authRouter');
const userRouter = require('./userRouter');
const chatRouter = require('./chatRouter');
const productTypeRouter = require('./productTypeRouter');
const attributeRouter = require('./attributeRouter');
const productRouter = require('./productRouter');
const cloudinaryRouter = require('./cloudinary');
const orderRouter = require('./orderRouter');
const cartRouter = require('./cartRouter');
const dashboardRouter = require('./dashboardRouter');
const articleRouter = require('./articleRouter');
const systemSettingsRouter = require('./systemSettingsRouter');
const warehouseRouter = require('./warehouseRouter');
const contactRouter = require('./contactRouter');
const vnpayRouter = require('./vnpayRouter');
const aiAdvisorRouter = require('./aiAdvisorRouter');
const returnRouter = require('./returnRouter');
const supplierRouter = require('./supplierRouter');
const router = express.Router();

router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/chat', chatRouter);
router.use('/product-types', productTypeRouter);
router.use('/attributes', attributeRouter);
router.use('/cloudinary', cloudinaryRouter);
router.use('/products', productRouter);
router.use('/orders', orderRouter);
router.use('/cart', cartRouter);
router.use('/dashboard', dashboardRouter);
router.use('/articles', articleRouter);
router.use('/settings', systemSettingsRouter);
router.use('/warehouse', warehouseRouter);
router.use('/contact', contactRouter);
router.use('/vnpay', vnpayRouter);
router.use('/ai', aiAdvisorRouter);
router.use('/returns', returnRouter);
router.use('/suppliers', supplierRouter);
module.exports = router;